service: user-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  versionFunctions: false
  stage: "dev"
  region: eu-central-1
  httpApi:
    cors: true

functions:
  signup:
    handler: app/handler.Signup
    events:
      - httpApi:
          path: /signup
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript
